# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get the score for a read/template pair under a given model at a particular
#' SNR value.
#'
#' @param ref A string that is the reference window we are aligning to.
#' @param read A list with elements name/read.
#'
#' @return Returns a list with the aligned read, ref and score
#' @export
getTransitionParameters <- function(tpl, mdl, snrs) {
    .Call('cc2r_getTransitionParameters', PACKAGE = 'cc2r', tpl, mdl, snrs)
}

#' Get the score for a read/template pair under a given model at a particular
#' SNR value.
#'
#' @param ref A string that is the reference window we are aligning to.
#' @param read A list with elements name/read.
#'
#' @return Returns a list with the aligned read, ref and score
#' @export
getScore <- function(read, tpl, mdl, pws, snrs) {
    .Call('cc2r_getScore', PACKAGE = 'cc2r', read, tpl, mdl, pws, snrs)
}

rcpp_hello <- function() {
    .Call('cc2r_rcpp_hello', PACKAGE = 'cc2r')
}

