# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesTwo <- function(x) {
    .Call('cc2r_timesTwo', PACKAGE = 'cc2r', x)
}

rcpp_hello <- function() {
    .Call('cc2r_rcpp_hello', PACKAGE = 'cc2r')
}

